/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package sd

import (
	cmap "github.com/orcaman/concurrent-map"
)

type instanceStore struct {
	dirty bool
	// the key is documentID, is value is mongo document.
	concurrentMap cmap.ConcurrentMap
	// the key is generated by indexFuncs,the value is a set of documentID.
	indexSets IndexCache
}

func init() {
	RegisterCacher(instance, newInstanceStore)
	InstIndexCols = NewIndexCols()
	InstIndexCols.AddIndexFunc(InstServiceIDIndex)
}

func newInstanceStore() *MongoCacher { _ = "STUB: not implemented"; return nil }

func (s *instanceStore) Name() string { _ = "STUB: not implemented"; return "" }

func (s *instanceStore) Size() int { _ = "STUB: not implemented"; return 0 }

func (s *instanceStore) Get(key string) interface{} { _ = "STUB: not implemented"; return nil }

func (s *instanceStore) ForEach(iter func(k string, v interface{}) (next bool)) {
	_ = "STUB: not implemented"
	return
}

func (s *instanceStore) GetValue(index string) []interface{} { _ = "STUB: not implemented"; return nil }

func (s *instanceStore) Dirty() bool { _ = "STUB: not implemented"; return false }

func (s *instanceStore) MarkDirty() { _ = "STUB: not implemented"; return }

func (s *instanceStore) Clear() { _ = "STUB: not implemented"; return }

func (s *instanceStore) ProcessUpdate(event MongoEvent) { _ = "STUB: not implemented"; return }

// set the document data.

// set the index sets.

func (s *instanceStore) ProcessDelete(event MongoEvent) { _ = "STUB: not implemented"; return }

func (s *instanceStore) isValueNotUpdated(value interface{}, newValue interface{}) bool {
	_ = "STUB: not implemented"
	return false
}

func InstServiceIDIndex(data interface{}) string { _ = "STUB: not implemented"; return "" }
