/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package sd

import (
	cmap "github.com/orcaman/concurrent-map"
)

type serviceStore struct {
	dirty bool
	// the key is documentID, is value is mongo document.
	concurrentMap cmap.ConcurrentMap
	// the key is generated by indexFuncs,the value is a set of documentID.
	indexSets IndexCache
}

func init() {
	RegisterCacher(service, newServiceStore)
	ServiceIndexCols = NewIndexCols()
	ServiceIndexCols.AddIndexFunc(ServiceIDIndex)
	ServiceIndexCols.AddIndexFunc(ServiceInfoIndex)
	ServiceIndexCols.AddIndexFunc(ServiceVersionIndex)
	ServiceIndexCols.AddIndexFunc(ServiceDomainProjectIndex)
}

func newServiceStore() *MongoCacher { _ = "STUB: not implemented"; return nil }

func (s *serviceStore) Name() string { _ = "STUB: not implemented"; return "" }

func (s *serviceStore) Size() int { _ = "STUB: not implemented"; return 0 }

func (s *serviceStore) Get(key string) interface{} { _ = "STUB: not implemented"; return nil }

func (s *serviceStore) ForEach(iter func(k string, v interface{}) (next bool)) {
	_ = "STUB: not implemented"
	return
}

func (s *serviceStore) GetValue(index string) []interface{} { _ = "STUB: not implemented"; return nil }

func (s *serviceStore) Dirty() bool { _ = "STUB: not implemented"; return false }

func (s *serviceStore) MarkDirty() { _ = "STUB: not implemented"; return }

func (s *serviceStore) Clear() { _ = "STUB: not implemented"; return }

func (s *serviceStore) ProcessUpdate(event MongoEvent) { _ = "STUB: not implemented"; return }

// set the document data.

// set the index sets.

func (s *serviceStore) ProcessDelete(event MongoEvent) { _ = "STUB: not implemented"; return }

func (s *serviceStore) isValueNotUpdated(value interface{}, newValue interface{}) bool {
	_ = "STUB: not implemented"
	return false
}

func ServiceIDIndex(data interface{}) string { _ = "STUB: not implemented"; return "" }

func ServiceInfoIndex(data interface{}) string { _ = "STUB: not implemented"; return "" }

func ServiceVersionIndex(data interface{}) string { _ = "STUB: not implemented"; return "" }

func ServiceDomainProjectIndex(data interface{}) string { _ = "STUB: not implemented"; return "" }
